pipeline{
    agent any 
    stages{
        stage('git repo checkout'){
            steps{
                git branch: 'main', changelog: false, poll: false, url: 'https://github.com/Pavangowda73/jenkins-tutorial'
            }
        }
        stage('compile the code'){
            steps{
                dir('4-python-jenkins-docker-app') {
                    sh 'python3 -m py_compile app.py'
                    }
            }
        }
        stage('runt unit test'){
            steps{
                dir('4-python-jenkins-docker-app') {
                    sh 'python3 -m unittest discover tests'
                    }
            }
        }
         stage('Docker build'){
            steps{
                dir('4-python-jenkins-docker-app') {
                    sh 'docker build -t sample-python-app .'
                    }
            }
        }
         stage('Docker login, tag, push'){
            steps{
                dir('4-python-jenkins-docker-app') {
                     withCredentials([usernamePassword(credentialsId: 'pavan73384', passwordVariable: 'DOCKER_HUB_PASS', usernameVariable: 'DOCKER_HUB_USER')]) {
                        sh '''
                             echo "$DOCKER_HUB_PASS" | docker login -u "$DOCKER_HUB_USER" --password-stdin
                             docker tag sample-python-app pavan73384/sample-python-app:V1
                             docker push pavan73384/sample-python-app:V1
                          '''
                         }
                }     
            }
        }
        stage('Clean work space'){
            steps{
                dir('4-python-jenkins-docker-app'){
                    cleanWs()
                }
            }
        }
    }
    post{
        success{
            emailext(
                subject:"Jenkins Job SUCCESS ${env.JOB_NAME}✌️👌👍😃",
                body:"Build Success\nJob: ${env.JOB_NAME}\nBuild_Number: ${env.BUILD_NUMBER}",
                to:"pavanpavan073384@gmail.com"
                )
        }
        failure{
            emailext(
                subject:"Jenkins Job FAILURE ${env.JOB_NAME}😥🤦",
                body:"Build Failure\nJob: ${env.JOB_NAME}\nBuild_Number: ${env.BUILD_NUMBER}",
                to:"pavanpavan073384@gmail.com"
                )
        }
    }
}
